# Variables for the staging environment
db_host: 127.0.0.1
db_database: laravel_staging
db_username: sail_staging
db_password: "hello_staging_123" # Use quotes for passwords
app_env: staging
app_url: http://staging.testproject.pipeworker.me/
app_domain: staging.testproject.pipeworker.me
redis_pass: "redis_staging_pass_123"
project_root: /mnt/data/bislinker/staging/app-code